{{- if not .Values.parameter.ingress.oauth.enable }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-{{ .Values.app.appName }}-ws
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/tls-acme: "true"
    traefik.ingress.kubernetes.io/router.middlewares: {{ range $index, $element := .Values.middleware.names }}{{ if $index }},{{ end }}{{ $.Release.Name }}-{{ $element }}{{ end }}
spec:
  rules:
  - host: {{ .Values.parameter.appHost }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.app.appName }}-service
            port:
              number: {{ .Values.app.deployment.container.ports.containerPort }}
  tls:
  - hosts:
    - {{ .Values.parameter.appHost }}
    secretName: {{ .Release.Name }}-tls
{{- end }}