{{- if not .Values.parameter.ingress.oauth.enable }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: basic-auth
  namespace: {{ .Release.Namespace }}
spec:
  basicAuth:
    secret: {{ .Release.Name }}-basic-auth
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: ipallowlist
  namespace: {{ .Release.Namespace }}
spec:
  ipWhiteList:
    sourceRange:
      - 212.8.208.204/32
      - 178.208.118.42/32
      - 212.8.208.194/32
      - 212.8.208.192/28
{{- end}}
