apiVersion: v1
data:
  MAIL_CLIENT_USER: {{ .Values.secrets.mail_client_user | b64enc }}
kind: Secret
metadata:
  creationTimestamp: null
  name: mail-client-user
  namespace: {{.Release.Namespace }}
---
apiVersion: v1
data:
  MAIL_CLIENT_PASSWORD: {{ .Values.secrets.mail_client_password | b64enc }}
kind: Secret
metadata:
  creationTimestamp: null
  name: mail-client-password
  namespace: {{.Release.Namespace }}
