apiVersion: v1
data:
  X_VERTRIEB_USER: {{ .Values.secrets.x_vertrieb_user | b64enc }}
kind: Secret
metadata:
  creationTimestamp: null
  name: x-vertrieb-user
  namespace: {{.Release.Namespace }}
---
apiVersion: v1
data:
  X_VERTRIEB_PW: {{ .Values.secrets.x_vertrieb_password | b64enc }}
kind: Secret
metadata:
  creationTimestamp: null
  name: x-vertrieb-password
  namespace: {{.Release.Namespace }}
