apiVersion: v1
data:
  SSO_API_USER: {{ .Values.secrets.sso_api_user | b64enc }}
kind: Secret
metadata:
  creationTimestamp: null
  name: sso-api-user
  namespace: {{.Release.Namespace }}
---
apiVersion: v1
data:
  SSO_API_PASSWORD: {{ .Values.secrets.sso_api_password | b64enc }}
kind: Secret
metadata:
  creationTimestamp: null
  name: sso-api-password
  namespace: {{.Release.Namespace }}
