apiVersion: v1
data:
  MSSQL_USER: {{ .Values.secrets.mssql_user }}
kind: Secret
metadata:
  creationTimestamp: null
  name: mssql-user
  namespace: live-db
---
apiVersion: v1
data:
  MSSQL_PW : {{ .Values.secrets.mssql_pw  }}
kind: Secret
metadata:
  creationTimestamp: null
  name: mssql-pw
  namespace: live-db
---
apiVersion: v1
data:
  MSSQL_HOST : {{ .Values.secrets.mssql_host }}
kind: Secret
metadata:
  creationTimestamp: null
  name: mssql-host
  namespace: live-db