apiVersion: apps/v1
kind: Deployment
metadata:
  name: live-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: live-dashboard
  template:
    metadata:
      labels:
        app: live-dashboard
    spec:
      containers:
        - name: live-dashboard
          image: "{{ .Values.liveDashboard.deployment.container.image }}:{{ .Values.liveDashboard.deployment.container.tag }}"
          imagePullPolicy: {{ .Values.liveDashboard.deployment.container.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.liveDashboard.deployment.container.ports.containerPort }}
          envFrom: {{ range $index, $element := .Values.liveDashboard.deployment.container.envFrom }}
            - secretRef:
                name: {{ $element.name }}{{ end }}
          env: {{ range $index, $element := .Values.liveDashboard.deployment.container.env }}
            - name: {{ $element.name }}
              value: {{ $element.value }}
            {{ end }}
      imagePullSecrets: [{name: docker-pull-secret}]
