apiVersion: v1
data:
    BLOB_ACCOUNT_KEY_PROD: {{ .Values.secrets.blob_account_key_prod | b64enc }}
kind: Secret
metadata:
    creationTimestamp: null
    name: blob-account-key-prod
    namespace: {{.Release.Namespace }}
---
apiVersion: v1
data:
    BLOB_ACCOUNT_KEY_DEV: {{ .Values.secrets.blob_account_key_dev | b64enc }}
kind: Secret
metadata:
    creationTimestamp: null
    name: blob-account-key-dev
    namespace: {{.Release.Namespace }}
