apiVersion: v1
data:
    TOKEN_SECRET: {{ .Values.secrets.fernet_token_secret }}
kind: Secret
metadata:
    creationTimestamp: null
    name: fernet-token-secret
    namespace: {{.Release.Namespace }}