kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  name: docker-pull-secret
  labels:
    app: app-name
data:
  .dockerconfigjson: {{ .Values.secrets.dockerPullSecret }}
---
apiVersion: v1
data:
  registry-auth-file: {{ .Values.secrets.basicAuthFile.htpasswd }}
kind: Secret
metadata:
  name: {{ .Release.Name }}-basic-auth
type: Opaque
