apiVersion: v1
data:
  mail_user: {{ .Values.secrets.mail_user | b64enc }}
kind: Secret
metadata:
  creationTimestamp: null
  name: mail-user
  namespace: {{.Release.Namespace }}
---
apiVersion: v1
data:
  mail_pw: {{ .Values.secrets.mail_pw | b64enc }}
kind: Secret
metadata:
  creationTimestamp: null
  name: mail-pw
  namespace: {{.Release.Namespace }}