apiVersion: v1
data:
    open_ai_key_bi: {{ .Values.secrets.open_ai_key_bi | b64enc }}
kind: Secret
metadata:
    creationTimestamp: null
    name: open-ai-key-bi
    namespace: {{.Release.Namespace }}