apiVersion: v1
data:
    shopware_api_token: {{ .Values.secrets.shopware_api_token | b64enc }}
kind: Secret
metadata:
    creationTimestamp: null
    name: shopware-api-token
    namespace: {{.Release.Namespace }}