apiVersion: v1
data:
    DJANGO_SNOWFLAKE_RSA_KEY: {{ .Values.secrets.snowflake_private_key }}
kind: Secret
metadata:
    creationTimestamp: null
    name: snowflake-private-key
    namespace: {{.Release.Namespace }}