apiVersion: v1
data:
  KAFKA_CA_CERT: {{ .Values.secrets.kafka_ca_cert | b64enc }}
kind: Secret
metadata:
  creationTimestamp: null
  name: kafka-ca-cert
  namespace: upscore-kafka

---

apiVersion: v1
data:
  KAFKA_SERVICE_KEY: {{ .Values.secrets.kafka_service_key | b64enc }}
kind: Secret
metadata:
  creationTimestamp: null
  name: kafka-service-key
  namespace: upscore-kafka

---

apiVersion: v1
data:
  KAFKA_SERVICE_CERT: {{ .Values.secrets.kafka_service_cert | b64enc }}
kind: Secret
metadata:
  creationTimestamp: null
  name: kafka-service-cert
  namespace: upscore-kafka