apiVersion: v1
data:
    TRUSTSTORE_PW: {{ .Values.secrets.truststore_pw | b64enc }}
kind: Secret
metadata:
    creationTimestamp: null
    name: kafka-truststore-pw
    namespace: upscore-kafka
    
---
apiVersion: v1
data:
    KAFKA_KEY_STORE_PW: {{ .Values.secrets.kafka_key_store_pw | b64enc }}
kind: Secret
metadata:
    creationTimestamp: null
    name: kafka-key-store-pw
    namespace: upscore-kafka
---
apiVersion: v1
data:
    KAFKA_SNOWFLAKE_RSA_KEY: {{ .Values.secrets.snowflake_private_key | b64enc }}
kind: Secret
metadata:
    creationTimestamp: null
    name: snowflake-private-key
    namespace: upscore-kafka