apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.appName }}-service
spec:
  ports:
  - port: {{ .Values.app.deployment.container.ports.containerPort }}
    targetPort: {{ .Values.app.deployment.container.ports.containerPort }}
  selector:
    app: {{ .Values.app.appName }}