liveDashboard:
  deployment:
    container:
      name: live-dashboard
      image: ghcr.io/nw-bi/live-dashboard
      tag: latest
      imagePullPolicy: Always
      ports:
        containerPort: 8000
      envFrom: []
      env: []
parameter:
  livedbhost: ~
  livedbnamespace: ~
middleware:
  names:
    - ipallowlist@kubernetescrd
    - basic-auth@kubernetescrd
