image:
  repository: mysql
  tag: "8.0"
  pullPolicy: IfNotPresent

mysqlRootPassword: "rootpassword"
mysqlDatabase: "mydb"
mysqlUser: "user"
mysqlPassword: "password"

service:
  type: ClusterIP
  port: 3306

persistence:
  enabled: true
  size: 10Gi
  storageClass: ""