apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-ingress-route-https
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`{{ .Values.parameters.dagsterHost }}`)
    middlewares:
      - name: {{ .Release.Name }}-basic-auth
    priority: 10
    services:
    - name: {{ .Release.Name }}-dagster-webserver
      port: 80

