apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-ingress-route-http
spec:
  entryPoints:
    - web
  routes:
  - kind: Rule
    match: Host(`{{ .Values.parameters.dagsterHost }}`)
    priority: 10
    middlewares:
      - name: redirect-https
    services:
    - name: {{ .Release.Name }}-dagster-webserver
      port: 80
