apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-https
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}-basic-auth
spec:
  basicAuth:
    secret: {{ .Release.Name }}-basic-auth
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: test-ipallowlist
spec:
  ipWhiteList:
    sourceRange:
      - 212.8.208.204/32
      - 178.208.118.42/32
      - 212.8.208.194/32