apiVersion: v1
data:
  DBT_SNOWFLAKE_ROLE: {{ .Values.dbtSnowflakeRole }}
kind: Secret
metadata:
  creationTimestamp: null
  name: dagster-snowflake-role
  namespace: dagster
---
apiVersion: v1
data:
  DBT_SNOWFLAKE_ROLE: {{ .Values.dbtSnowflakeRole_stage }}
kind: Secret
metadata:
  creationTimestamp: null
  name: dagster-snowflake-role-stage
  namespace: dagster