apiVersion: v1
data:
  AVS_SFTP_SERVERNAME: {{ .Values.secrets.avs_sftp_servername }}
kind: Secret
metadata:
  creationTimestamp: null
  name: avs-sftp-servername
  namespace: dagster
---
apiVersion: v1
data:
  AVS_SFTP_PW: {{ .Values.secrets.avs_sftp_pw }}
kind: Secret
metadata:
  creationTimestamp: null
  name: avs-sftp-pw
  namespace: dagster
---
apiVersion: v1
data:
  AVS_SFTP_BENUTZER: {{ .Values.secrets.avs_sftp_benutzer }}
kind: Secret
metadata:
  creationTimestamp: null
  name: avs-sftp-benutzer
  namespace: dagster
