apiVersion: v1
data:
  aschendorff_sftp_server: {{ .Values.secrets.aschendorff_sftp_server | b64enc }}
kind: Secret
metadata:
  creationTimestamp: null
  name: aschendorff-sftp-server
  namespace: dagster
---

apiVersion: v1
data:
  aschendorff_sftp_user: {{ .Values.secrets.aschendorff_sftp_user | b64enc }}
kind: Secret
metadata:
  creationTimestamp: null
  name: aschendorff-sftp-user
  namespace: dagster
---

apiVersion: v1
data:
  aschendorff_sftp_pw: {{ .Values.secrets.aschendorff_sftp_pw | b64enc }}
kind: Secret
metadata:
  creationTimestamp: null
  name: aschendorff-sftp-pw
  namespace: dagster
