apiVersion: v1
data:
  FK_WEBCRALLER_NW_LISTINGS: {{ .Values.fkWebcrallerListings }}
kind: Secret
metadata:
  creationTimestamp: null
  name: fk-webcraller-nw-listings
  namespace: dagster
---
apiVersion: v1
data:
  FK_WEBCRALLER_NW_LISTINGS: {{ .Values.fkWebcrallerListings_stage }}
kind: Secret
metadata:
  creationTimestamp: null
  name: fk-webcraller-nw-listings-stage
  namespace: dagster