apiVersion: v1
data:
  kfm_sftp_user: {{ .Values.secrets.kfm_sftp_user | b64enc }}
kind: Secret
metadata:
  creationTimestamp: null
  name: kfm-sftp-user
  namespace: dagster
---
apiVersion: v1
data:
  kfm_sftp_pw : {{ .Values.secrets.kfm_sftp_pw | b64enc }}
kind: Secret
metadata:
  creationTimestamp: null
  name: kfm-sftp-pw
  namespace: dagster
