apiVersion: v1
data:
  ABO_SHOP_USER: {{ .Values.secrets.abo_shop_sftp_user | b64enc }}
kind: Secret
metadata:
  creationTimestamp: null
  name: abo-shop-sftp-user
  namespace: dagster
---
apiVersion: v1
data:
  ABO_SHOP_PASSWORD: {{ .Values.secrets.abo_shop_sftp_pw | b64enc }}
kind: Secret
metadata:
  creationTimestamp: null
  name: abo-shop-sftp-pw
  namespace: dagster