apiVersion: v1
data:
  DBT_TARGET: {{ .Values.dbt_target }}
kind: Secret
metadata:
  creationTimestamp: null
  name: dagster-dbt-target
  namespace: dagster
---
apiVersion: v1
data:
  DBT_TARGET: {{ .Values.dbt_target_stage }}
kind: Secret
metadata:
  creationTimestamp: null
  name: dagster-dbt-target-stage
  namespace: dagster