apiVersion: v1
data:
  mip_jira_server: {{ .Values.secrets.mip_jira_server | b64enc }}
kind: Secret
metadata:
  creationTimestamp: null
  name: mip-jira-server
  namespace: dagster
---

apiVersion: v1
data:
  mip_jira_user: {{ .Values.secrets.mip_jira_user | b64enc }}
kind: Secret
metadata:
  creationTimestamp: null
  name: mip-jira-user
  namespace: dagster
---

apiVersion: v1
data:
  mip_jira_pw: {{ .Values.secrets.mip_jira_pw | b64enc }}
kind: Secret
metadata:
  creationTimestamp: null
  name: mip-jira-pw
  namespace: dagster
