apiVersion: v1
data:
  BDL_SERVER: {{ .Values.BDL_SERVER | b64enc }}
kind: Secret
metadata:
  creationTimestamp: null
  name: bdl-server
  namespace: dagster
---
apiVersion: v1
data:
  BDL_PW: {{ .Values.BDL_PW | b64enc }}
kind: Secret
metadata:
  creationTimestamp: null
  name: bdl-pw
  namespace: dagster
---
apiVersion: v1
data:
  BDL_USER: {{ .Values.BDL_USER | b64enc }}
kind: Secret
metadata:
  creationTimestamp: null
  name: bdl-user
  namespace: dagster
