apiVersion: v1
data:
  TARGET: {{ .Values.secrets.dagster_target }}
kind: Secret
metadata:
  creationTimestamp: null
  name: dagster-target
  namespace: dagster
---
apiVersion: v1
data:
  TARGET: {{ .Values.secrets.dagster_target_stage }}
kind: Secret
metadata:
  creationTimestamp: null
  name: dagster-target-stage
  namespace: dagster