apiVersion: v1
data:
    DBT_SNOWFLAKE_PW: {{ .Values.dbtSnowflakePassword }}
kind: Secret
metadata:
    creationTimestamp: null
    name: dagster-snowflake-password
    namespace: dagster
---
apiVersion: v1
data:
    DBT_SNOWFLAKE_PW: {{ .Values.dbtSnowflakePassword_stage }}
kind: Secret
metadata:
    creationTimestamp: null
    name: dagster-snowflake-password-stage
    namespace: dagster
---
apiVersion: v1
data:
    snowflake_p8_key: {{ .Values.snowflake_p8_key }}
kind: Secret
metadata:
    creationTimestamp: null
    name: snowflake-p8-key
    namespace: dagster