apiVersion: v1
data:
  mip_sftp_server: {{ .Values.secrets.sftp_mip_server }}
kind: Secret
metadata:

  creationTimestamp: null
  name: sftp-die-glocke-server
  namespace: dagster
---
apiVersion: v1
data:
  glocke_sftp_pw: {{ .Values.secrets.sftp_die_glocke_pw }}
kind: Secret
metadata:

  creationTimestamp: null
  name: sftp-die-glocke-pw
  namespace: dagster
---

apiVersion: v1
data:
  glocke_sftp_user: {{ .Values.secrets.sftp_die_glocke }}
kind: Secret
metadata:

  creationTimestamp: null
  name: sftp-die-glocke-user
  namespace: dagster

