apiVersion: v1
data:
  ELESTIO_MATOMO_USER: {{ .Values.secrets.elestio_matomo_user | b64enc }}
kind: Secret
metadata:
  creationTimestamp: null
  name: elestio-matomo-user
  namespace: dagster
---
apiVersion: v1
data:
  ELESTIO_MATOMO_PASSWORD: {{ .Values.secrets.elestio_matomo_password | b64enc }}
kind: Secret
metadata:
  creationTimestamp: null
  name: elestio-matomo-password
  namespace: dagster
---
apiVersion: v1
data:
  ELESTIO_MATOMO_CA_CERT: {{ .Values.secrets.elestio_matomo_ca_cert | b64enc }}
kind: Secret
metadata:
  creationTimestamp: null
  name: elestio-matomo-ca-cert
  namespace: dagster
