dagster:
  dagsterWebserver:
    pathPrefix: /dagster
    readinessProbe:
      httpGet:
        path: /dagster/server_info

    workspace:
      enabled: true
 
  dagsterDaemon:
    runRetries:
      enabled: false
    sensors:
      numWorkers: 3
    # securityContext:
    #   sysctls:
    #     - name: net.ipv4.tcp_keepalive_time
    #       value: "1205"

    schedules:
      numWorkers: 6
  dagster-user-deployments:
    enabled: true
    enableSubchart: false

parameters:
  use_oauth: true
  dagsterHost: dagster